# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        r-version: [4.4]

    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Set up R
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: System libs 
        # uses: ConorMacBride/install-package@v1
        # with:
        #   brew: freetype udunits cairo harfbuzz fribidi libpng libtiff jpeg gdal pkg-config libbzip2
        #   brew-cask: freetype udunits cairo harfbuzz fribidi libpng libtiff jpeg gdal pkg-config libbzip2
        #   apt: libfontconfig1-dev libudunits2-dev libcairo2-dev libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libgdal-dev libgeos-dev libproj-dev libbz2-dev
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install EJAM
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages("remotes")
          remotes::install_github("USEPA/EJAM-open")
        shell: Rscript {0}

      - name: Test Installation
        run: |
          R -e 'library(EJAM); print("Package loaded successfully")'
