name: EJAM Installation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install_ejam:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        r-version: [4.3, 4.4]
        install-method: [github, url]  # Matrix for installation method

    steps:
      - name: Checkout test-EJAM-install repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # Step to pull DESCRIPTION file from EJAM-open repository
      - name: Fetch EJAM-open DESCRIPTION file
        run: |
          curl -o DESCRIPTION https://raw.githubusercontent.com/USEPA/EJAM-open/main/DESCRIPTION

      # Extract and hash Imports and Suggests
      - name: Generate hash of Imports and Suggests
        id: dependency-hash
        run: |
          # Extract the Imports and Suggests fields from DESCRIPTION
          imports=$(awk '/Imports:/ {print substr($0, index($0,$2))}' DESCRIPTION)
          suggests=$(awk '/Suggests:/ {print substr($0, index($0,$2))}' DESCRIPTION)
          deps=$(echo "$imports,$suggests" | sed 's/,/\n/g' | sed 's/^[ \t]*//g' | tr '\n' ',' | sed 's/,$//')
          hash=$(echo -n "$deps" | md5sum | cut -d ' ' -f1)
          echo "hash=$hash" >> $GITHUB_ENV
        
      # Use the hash in the cache key
      - name: Restore R package cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}
          key: ${{ runner.os }}-R-${{ matrix.r-version }}-${{ env.hash }}
          restore-keys: ${{ runner.os }}-R-${{ matrix.r-version }}-
          
      - name: System libs 
        uses: ConorMacBride/install-package@v1
        with:
          brew: freetype udunits cairo harfbuzz fribidi libpng libtiff jpeg gdal pkg-config
          brew-cask: freetype udunits cairo harfbuzz fribidi libpng libtiff jpeg gdal pkg-config
          apt: libfontconfig1-dev libudunits2-dev libcairo2-dev libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libgdal-dev libgeos-dev libproj-dev

      # Install EJAM package (either from GitHub or URL based on the matrix value)
      - name: Install EJAM (method- ${{ matrix.install-method }})
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages("remotes")
          if("${{ matrix.install-method }}" == "github") {
            remotes::install_github("USEPA/EJAM-open", dependencies=TRUE, force=TRUE)
          } else {
            remotes::install_url(url = "https://github.com/USEPA/EJAM-open/archive/refs/tags/v2.32-EJAM-open.tar.gz",
                                 dependencies = TRUE, upgrade = "never", 
                                 build = FALSE, build_manual = FALSE, build_vignettes = FALSE)
          }
        shell: Rscript {0}

      # Use the hash in the cache key
      - name: Restore R package cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}
          key: ${{ runner.os }}-R-${{ matrix.r-version }}-${{ env.hash }}
          restore-keys: ${{ runner.os }}-R-${{ matrix.r-version }}-

      - name: Test Installation
        run: |
          R -e 'library(EJAM); print("Package loaded successfully")'
